### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by jobasc0** [forxer/generic-term-translations-for-laravel#8]
i am getting this error 

Problem 1
    - Root composer.json requires forxer/generic-term-translations-for-laravel * -> satisfiable by forxer/generic-term-translations-for-laravel[1.0, ..., 1.3.0].
    - forxer/generic-term-translations-for-laravel[1.0, ..., 1.3.0] require laravel-lang/publisher ^14.0 -> found laravel-lang/publisher[v14.0.0, ..., 14.7.1] but the package is fixed to 15.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by forxer** [comment]
It looks like you are using version 15 of `laravel-lang/publisher` but this package currently only has support for version 14

I'm going to open an issue to look into this.

**Comment by forxer** [comment]
See #9

**Comment by forxer** [comment]
Released 1.4.0
